In [34]:
# model tuning also know as hyperprarmeter tunning
#1:Cross valudation
#2: GridsearchCV
#3:randomsearchCV

In [35]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [36]:
df = pd.read_csv('encodeing_life_expectancy.csv')

In [37]:
df

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,...,Country_United States of America,Country_Uruguay,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela (Bolivarian Republic of),Country_Viet Nam,Country_Yemen,Country_Zambia,Country_Zimbabwe,Status_Developing
0,2015,65.0,263.0,55.0,0.01,71.279624,65.000000,1154,19.1,83,...,0,0,0,0,0,0,0,0,0,1
1,2014,59.9,271.0,55.0,0.01,73.523582,62.000000,492,18.6,86,...,0,0,0,0,0,0,0,0,0,1
2,2013,59.9,268.0,55.0,0.01,73.219243,64.000000,430,18.1,89,...,0,0,0,0,0,0,0,0,0,1
3,2012,59.5,272.0,55.0,0.01,78.184215,67.000000,2787,17.6,93,...,0,0,0,0,0,0,0,0,0,1
4,2011,59.2,275.0,55.0,0.01,7.097109,68.000000,3013,17.2,97,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,44.3,456.5,27.0,4.36,0.000000,68.000000,31,27.1,42,...,0,0,0,0,0,0,0,0,1,1
2934,2003,44.5,456.5,26.0,4.06,0.000000,58.351153,998,26.7,41,...,0,0,0,0,0,0,0,0,1,1
2935,2002,44.8,73.0,25.0,4.43,0.000000,73.000000,304,26.3,40,...,0,0,0,0,0,0,0,0,1,1
2936,2001,45.3,456.5,25.0,1.72,0.000000,76.000000,529,25.9,39,...,0,0,0,0,0,0,0,0,1,1
2937,2000,46.0,456.5,24.0,1.68,0.000000,79.000000,1483,25.5,39,...,0,0,0,0,0,0,0,0,1,1

In [38]:
df.rename(columns={'Life expectancy ':'Life expectancy'},inplace=True)

In [39]:
Y = df['Life expectancy']
X = df.drop(columns='Life expectancy',axis=1)

In [40]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=42)

In [41]:
from sklearn.preprocessing import StandardScaler

In [42]:
Scaler = StandardScaler()

In [43]:
X_train_sclar = Scaler.fit_transform(X_train)
X_test_sclar = Scaler.transform(X_test)

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
Liner_model = LinearRegression()
KNN_model = KNeighborsRegressor(n_neighbors=5)
DecisionTree_model = DecisionTreeRegressor(random_state=42)
random_model = RandomForestRegressor(random_state=42)

In [45]:
# Cross valuditon

In [46]:
from sklearn.model_selection import cross_val_score

In [47]:
model_dir ={}
models = [Liner_model,KNN_model,DecisionTree_model,random_model]
for model in models:
    score = cross_val_score(model,X_train_sclar,Y_train,scoring='neg_mean_squared_error',cv=5)
    print(f"{model}:{abs(score)} mean_value::{np.mean(abs(score))}")
    model_dir[model]=float(np.mean(abs(score)))
value =(model_dir.values())
best_model = min(model_dir, key=model_dir.get)
print(f"the best model::{best_model}")
print(f"the less error model::{min(value)}")

LinearRegression():[2.33293619e+24 2.37353627e+24 2.10359402e+24 1.07286267e+25
 1.04076588e+25] mean_value::5.589270409110639e+24
KNeighborsRegressor():[6.87405696 5.73566094 5.40046202 5.64326532 6.99719389] mean_value::6.130127826547681
DecisionTreeRegressor(random_state=42):[8.00782535 7.08870999 6.5786383  6.8838674  7.71968414] mean_value::7.255745035480848
RandomForestRegressor(random_state=42):[3.9052162  3.11044283 3.21588279 4.0942504  4.76753367] mean_value::3.81866517787617
the best model::RandomForestRegressor(random_state=42)
the less error model::3.81866517787617

In [48]:
#model.coinf_

In [49]:
## gridsearchcv

In [50]:
from sklearn.model_selection import GridSearchCV

In [51]:
random_model

RandomForestRegressor(random_state=42)

In [52]:
hyperpartmeter={
'n_estimators':[50,100],
'criterion': ['squared_error'],
'max_depth':[90]
}

In [73]:
testing_grid = GridSearchCV(estimator=random_model,cv=5, param_grid=hyperpartmeter,scoring='neg_mean_squared_error')

In [75]:
testing_grid

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
             param_grid={'criterion': ['squared_error'], 'max_depth': [90],
                         'n_estimators': [50, 100]},
             scoring='neg_mean_squared_error')

In [77]:
testing_grid.fit(X_train_sclar,Y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
             param_grid={'criterion': ['squared_error'], 'max_depth': [90],
                         'n_estimators': [50, 100]},
             scoring='neg_mean_squared_error')

In [78]:
testing_grid.best_params_

{'criterion': 'squared_error', 'max_depth': 90, 'n_estimators': 100}

In [79]:
abs(testing_grid.best_score_)

3.81866517787617

In [80]:
random_model=RandomForestRegressor(criterion='squared_error', max_depth=90, n_estimators=100,random_state=42)

In [81]:
random_model.fit(X_train,Y_train)

RandomForestRegressor(max_depth=90, random_state=42)

In [82]:
Y_pred =random_model.predict(X_test)

In [83]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [84]:
print(r2_score(Y_test,Y_pred))

0.9690835008710987

In [85]:
metrics = [r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error]

for metric in metrics:
    print(f"{metric.__name__}: {metric(Y_test, Y_pred)}")

r2_score: 0.9690835008710987
mean_absolute_error: 1.0389192246570766
mean_squared_error: 2.678459463040148
root_mean_squared_error: 1.636599970377657

In [86]:
X_train_predit = random_model.predict(X_train)

In [87]:
print(mean_absolute_error(X_train_predit,Y_train))

0.42510346122544007

In [88]:
testing_grid.cv_results_

{'mean_fit_time': array([1.06941018, 2.16776805]),
 'std_fit_time': array([0.01449903, 0.07923478]),
 'mean_score_time': array([0.00622625, 0.01219316]),
 'std_score_time': array([0.00048483, 0.00194716]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error'],
              mask=[False, False],
        fill_value='?',
             dtype=object),
 'param_max_depth': masked_array(data=[90, 90],
              mask=[False, False],
        fill_value=999999),
 'param_n_estimators': masked_array(data=[50, 100],
              mask=[False, False],
        fill_value=999999),
 'params': [{'criterion': 'squared_error',
   'max_depth': 90,
   'n_estimators': 50},
  {'criterion': 'squared_error', 'max_depth': 90, 'n_estimators': 100}],
 'split0_test_score': array([-3.81843391, -3.9052162 ]),
 'split1_test_score': array([-3.24912383, -3.11044283]),
 'split2_test_score': array([-3.26926556, -3.21588279]),
 'split3_test_score': array([-4.11628008, -4.0942504 ]),
 'split4_test_score': array([-4.67807751, -4.76753367]),
 'mean_test_score': array([-3.82623618, -3.81866518]),
 'std_test_score': array([0.53909089, 0.608065  ]),
 'rank_test_score': array([2, 1])}

In [89]:
result = pd.DataFrame(testing_grid.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.069410,0.014499,0.006226,0.000485,squared_error,90,50,"{'criterion': 'squared_error', 'max_depth': 90...",-3.818434,-3.249124,-3.269266,-4.11628,-4.678078,-3.826236,0.539091,2
1,2.167768,0.079235,0.012193,0.001947,squared_error,90,100,"{'criterion': 'squared_error', 'max_depth': 90...",-3.905216,-3.110443,-3.215883,-4.09425,-4.767534,-3.818665,0.608065,1

In [91]:
# randomsearchcv

In [92]:
from sklearn.model_selection import RandomizedSearchCV

In [101]:
hyperpartmeter={
'n_estimators':[50,100,140,150],
'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
'max_depth':[90,56,76,56]
}

In [103]:
testing_reandomcv = RandomizedSearchCV(estimator=random_model,cv=5,random_state=42,scoring='neg_mean_squared_error',param_distributions=hyperpartmeter,n_iter=4)

In [115]:
testing_reandomcv.fit(X_train,Y_train)

RandomizedSearchCV(cv=5,
                   estimator=RandomForestRegressor(max_depth=90,
                                                   random_state=42),
                   n_iter=4,
                   param_distributions={'criterion': ['squared_error',
                                                      'absolute_error',
                                                      'friedman_mse',
                                                      'poisson'],
                                        'max_depth': [90, 56, 76, 56],
                                        'n_estimators': [50, 100, 140, 150]},
                   random_state=42, scoring='neg_mean_squared_error')

In [109]:
testing_reandomcv.cv_results_

{'mean_fit_time': array([1.24873476, 3.73844242, 1.0320487 , 1.00407867]),
 'std_fit_time': array([0.0239301 , 0.05213115, 0.02186804, 0.01146696]),
 'mean_score_time': array([0.00730672, 0.01655078, 0.00709357, 0.0076046 ]),
 'std_score_time': array([0.00041495, 0.00186238, 0.00065791, 0.00107234]),
 'param_n_estimators': masked_array(data=[50, 140, 50, 50],
              mask=[False, False, False, False],
        fill_value=999999),
 'param_max_depth': masked_array(data=[56, 76, 90, 56],
              mask=[False, False, False, False],
        fill_value=999999),
 'param_criterion': masked_array(data=['poisson', 'poisson', 'squared_error', 'friedman_mse'],
              mask=[False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_estimators': 50, 'max_depth': 56, 'criterion': 'poisson'},
  {'n_estimators': 140, 'max_depth': 76, 'criterion': 'poisson'},
  {'n_estimators': 50, 'max_depth': 90, 'criterion': 'squared_error'},
  {'n_estimators': 50, 'max_depth': 56, 'criterion': 'friedman_mse'}],
 'split0_test_score': array([-3.83642018, -3.8824217 , -3.80442165, -3.89243509]),
 'split1_test_score': array([-3.37826638, -3.1976356 , -3.28352762, -3.24118315]),
 'split2_test_score': array([-3.1962938 , -3.14607945, -3.26916405, -3.30655937]),
 'split3_test_score': array([-4.03423759, -3.98241402, -4.08454552, -4.00600459]),
 'split4_test_score': array([-4.85431079, -4.84433313, -4.6905227 , -4.90846358]),
 'mean_test_score': array([-3.85990575, -3.81057678, -3.82643631, -3.87092916]),
 'std_test_score': array([0.58174597, 0.61977343, 0.53273868, 0.6017107 ]),
 'rank_test_score': array([3, 1, 2, 4])}

In [113]:
pd.DataFrame(testing_reandomcv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,param_max_depth,param_criterion,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.248735,0.023930,0.007307,0.000415,50,56,poisson,"{'n_estimators': 50, 'max_depth': 56, 'criteri...",-3.836420,-3.378266,-3.196294,-4.034238,-4.854311,-3.859906,0.581746,3
1,3.738442,0.052131,0.016551,0.001862,140,76,poisson,"{'n_estimators': 140, 'max_depth': 76, 'criter...",-3.882422,-3.197636,-3.146079,-3.982414,-4.844333,-3.810577,0.619773,1
2,1.032049,0.021868,0.007094,0.000658,50,90,squared_error,"{'n_estimators': 50, 'max_depth': 90, 'criteri...",-3.804422,-3.283528,-3.269164,-4.084546,-4.690523,-3.826436,0.532739,2
3,1.004079,0.011467,0.007605,0.001072,50,56,friedman_mse,"{'n_estimators': 50, 'max_depth': 56, 'criteri...",-3.892435,-3.241183,-3.306559,-4.006005,-4.908464,-3.870929,0.601711,4