In [192]:
import pandas as pd

In [193]:
df=pd.read_csv("Superstore sales dataset.csv")

In [194]:
df.shape

(9994, 21)

In [195]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,8/11/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [196]:
df.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9992,9993,CA-2017-121258,26/2/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.320
9993,9994,CA-2017-119914,4/5/2017,9/5/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

In [197]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [198]:
df.index

RangeIndex(start=0, stop=9994, step=1)

In [199]:
pd.DataFrame([1,2,3],columns=['A'],index=['A','B','C'])

   A
A  1
B  2
C  3

In [200]:
pd.DataFrame((1,2,3))

   0
0  1
1  2
2  3

In [201]:
pd.DataFrame({"Months":["jan","Feb"],"Sales":[20,40]})

  Months  Sales
0    jan     20
1    Feb     40

In [202]:
import numpy as np
np.random.seed(121)
df=pd.DataFrame(np.random.randint(0,10,(3,3)))

In [203]:
"A B C".split()

['A', 'B', 'C']

In [204]:

np.random.seed(121)
df=pd.DataFrame(np.random.randint(0,10,(3,3)),columns="A B C".split(),index='P Q R'.split())
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [205]:
df

   A  B  C
P  2  5  8
Q  4  1  4
R  3  0  2

In [206]:
df=pd.read_csv("Superstore sales dataset.csv")

In [207]:
df[['Row ID','Order ID','Sales']].head(2)

   Row ID        Order ID   Sales
0       1  CA-2016-152156  261.96
1       2  CA-2016-152156  731.94

In [208]:
# df.iloc[rows,columns] used to accessing based on index

In [209]:
df.iloc[2:8,[2,5,7]]

   Order Date Customer ID    Segment
2   12/6/2016    DV-13045  Corporate
3  11/10/2015    SO-20335   Consumer
4  11/10/2015    SO-20335   Consumer
5    9/6/2014    BH-11710   Consumer
6    9/6/2014    BH-11710   Consumer
7    9/6/2014    BH-11710   Consumer

In [210]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [211]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [212]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [213]:
np.iinfo(np.int64)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [214]:
np.finfo(np.float16).min

-65500.0

In [215]:
df.select_dtypes(include=['int64','float64']).head(2)

   Row ID  Postal Code   Sales  Quantity  Discount    Profit
0       1        42420  261.96         2       0.0   41.9136
1       2        42420  731.94         3       0.0  219.5820

In [216]:
# df.select_dtypes(include=['str']).shape

In [217]:
df.shape

(9994, 21)

In [218]:
df.select_dtypes(include=['int64','float64']).shape

(9994, 6)

In [219]:
subset_df=df.iloc[0:5,0:5].copy()

In [220]:
subset_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode'], dtype='object')

In [221]:
subset_df[['Row ID','Order ID','Ship Mode','Ship Date']].min()

Row ID                    1
Order ID     CA-2016-138688
Ship Mode      Second Class
Ship Date        11/11/2016
dtype: object

In [222]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [223]:
df['Ship Mode'].str.upper().head(2)

0    SECOND CLASS
1    SECOND CLASS
Name: Ship Mode, dtype: object

In [224]:
df['Ship Mode'].str.lower().head(2)

0    second class
1    second class
Name: Ship Mode, dtype: object

In [225]:
df['Ship Mode'].str.capitalize().head(2)

0    Second class
1    Second class
Name: Ship Mode, dtype: object

In [226]:
df['Ship Mode'].str.title().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [227]:
"data Science".capitalize()

'Data science'

In [228]:
df['Ship Mode'].str.len().head(2)

0    12
1    12
Name: Ship Mode, dtype: int64

In [229]:
df['Ship Mode'].str.len().tail(2)

9992    14
9993    12
Name: Ship Mode, dtype: int64

In [230]:
df['Ship Mode'].str.strip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [231]:
 " data ".strip()

'data'

In [232]:
df['Ship Mode'].str.lstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [233]:
df['Ship Mode'].str.rstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: object

In [234]:
df['Ship Mode'].str.split(" ").str[0]

0         Second
1         Second
2         Second
3       Standard
4       Standard
          ...
9989      Second
9990    Standard
9991    Standard
9992    Standard
9993      Second
Name: Ship Mode, Length: 9994, dtype: object

In [235]:
"91-733833".split("-")

['91', '733833']

In [236]:
"data science".split("a")

['d', 't', ' science']

In [237]:
df['Ship Mode'].str.count("Second")

0       1
1       1
2       1
3       0
4       0
       ..
9989    1
9990    0
9991    0
9992    0
9993    1
Name: Ship Mode, Length: 9994, dtype: int64

In [238]:
df['Ship Mode'].str.pad(width=20,side='left',fillchar="-")

0       --------Second Class
1       --------Second Class
2       --------Second Class
3       ------Standard Class
4       ------Standard Class
                ...
9989    --------Second Class
9990    ------Standard Class
9991    ------Standard Class
9992    ------Standard Class
9993    --------Second Class
Name: Ship Mode, Length: 9994, dtype: object